/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTurmasRouteImport } from './routes/_authenticated/turmas'
import { Route as AuthenticatedPagamentosRouteImport } from './routes/_authenticated/pagamentos'
import { Route as AuthenticatedMensalidadesRouteImport } from './routes/_authenticated/mensalidades'
import { Route as AuthenticatedImportacaoRouteImport } from './routes/_authenticated/importacao'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedCobrancasRouteImport } from './routes/_authenticated/cobrancas'
import { Route as AuthenticatedAlunosRouteImport } from './routes/_authenticated/alunos'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTurmasRoute = AuthenticatedTurmasRouteImport.update({
  id: '/turmas',
  path: '/turmas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPagamentosRoute = AuthenticatedPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMensalidadesRoute =
  AuthenticatedMensalidadesRouteImport.update({
    id: '/mensalidades',
    path: '/mensalidades',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImportacaoRoute = AuthenticatedImportacaoRouteImport.update({
  id: '/importacao',
  path: '/importacao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCobrancasRoute = AuthenticatedCobrancasRouteImport.update({
  id: '/cobrancas',
  path: '/cobrancas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlunosRoute = AuthenticatedAlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/alunos': typeof AuthenticatedAlunosRoute
  '/cobrancas': typeof AuthenticatedCobrancasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/importacao': typeof AuthenticatedImportacaoRoute
  '/mensalidades': typeof AuthenticatedMensalidadesRoute
  '/pagamentos': typeof AuthenticatedPagamentosRoute
  '/turmas': typeof AuthenticatedTurmasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/alunos': typeof AuthenticatedAlunosRoute
  '/cobrancas': typeof AuthenticatedCobrancasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/importacao': typeof AuthenticatedImportacaoRoute
  '/mensalidades': typeof AuthenticatedMensalidadesRoute
  '/pagamentos': typeof AuthenticatedPagamentosRoute
  '/turmas': typeof AuthenticatedTurmasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/alunos': typeof AuthenticatedAlunosRoute
  '/_authenticated/cobrancas': typeof AuthenticatedCobrancasRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/importacao': typeof AuthenticatedImportacaoRoute
  '/_authenticated/mensalidades': typeof AuthenticatedMensalidadesRoute
  '/_authenticated/pagamentos': typeof AuthenticatedPagamentosRoute
  '/_authenticated/turmas': typeof AuthenticatedTurmasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/alunos'
    | '/cobrancas'
    | '/configuracoes'
    | '/dashboard'
    | '/importacao'
    | '/mensalidades'
    | '/pagamentos'
    | '/turmas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/alunos'
    | '/cobrancas'
    | '/configuracoes'
    | '/dashboard'
    | '/importacao'
    | '/mensalidades'
    | '/pagamentos'
    | '/turmas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/alunos'
    | '/_authenticated/cobrancas'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/importacao'
    | '/_authenticated/mensalidades'
    | '/_authenticated/pagamentos'
    | '/_authenticated/turmas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/turmas': {
      id: '/_authenticated/turmas'
      path: '/turmas'
      fullPath: '/turmas'
      preLoaderRoute: typeof AuthenticatedTurmasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pagamentos': {
      id: '/_authenticated/pagamentos'
      path: '/pagamentos'
      fullPath: '/pagamentos'
      preLoaderRoute: typeof AuthenticatedPagamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mensalidades': {
      id: '/_authenticated/mensalidades'
      path: '/mensalidades'
      fullPath: '/mensalidades'
      preLoaderRoute: typeof AuthenticatedMensalidadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/importacao': {
      id: '/_authenticated/importacao'
      path: '/importacao'
      fullPath: '/importacao'
      preLoaderRoute: typeof AuthenticatedImportacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cobrancas': {
      id: '/_authenticated/cobrancas'
      path: '/cobrancas'
      fullPath: '/cobrancas'
      preLoaderRoute: typeof AuthenticatedCobrancasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alunos': {
      id: '/_authenticated/alunos'
      path: '/alunos'
      fullPath: '/alunos'
      preLoaderRoute: typeof AuthenticatedAlunosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlunosRoute: typeof AuthenticatedAlunosRoute
  AuthenticatedCobrancasRoute: typeof AuthenticatedCobrancasRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedImportacaoRoute: typeof AuthenticatedImportacaoRoute
  AuthenticatedMensalidadesRoute: typeof AuthenticatedMensalidadesRoute
  AuthenticatedPagamentosRoute: typeof AuthenticatedPagamentosRoute
  AuthenticatedTurmasRoute: typeof AuthenticatedTurmasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlunosRoute: AuthenticatedAlunosRoute,
  AuthenticatedCobrancasRoute: AuthenticatedCobrancasRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedImportacaoRoute: AuthenticatedImportacaoRoute,
  AuthenticatedMensalidadesRoute: AuthenticatedMensalidadesRoute,
  AuthenticatedPagamentosRoute: AuthenticatedPagamentosRoute,
  AuthenticatedTurmasRoute: AuthenticatedTurmasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
